style:
  ForbiddenComment:
    active: false
  NewLineAtEndOfFile:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  WildcardImport:
    active: false
  MagicNumber:
    active: false
naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]