style:
  ForbiddenComment:
    active: false
  NewLineAtEndOfFile:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    ignoreAnnotated: [ 'Query' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]